### ISSUE TITLE
How to get "Data/BRATS/*.npy"

### ISSUE THREAD

**Issue by ImageWQ** [MrGiovanni/UNetPlusPlus#12]
I don't know how to get “BRATS2013_Syn_Flair_Train_X.npy” and “BRATS2013_Syn_Flair_Train_S.npy”. Please give me a brief explanation when you are free.
Thank you!

**Comment by mahfuzmohammad** [comment]
We generated those 2 files ourselves from BRATS 2013 dataset. We use synthetic flair images particularly and saved them with there ground truth masks in numpy files.  “BRATS2013_Syn_Flair_Train_X.npy” contains input images and “BRATS2013_Syn_Flair_Train_S.npy” contains segmentation masks only.

**Comment by lichen14** [comment]
> We generated those 2 files ourselves from BRATS 2013 dataset. We use synthetic flair images particularly and saved them with there ground truth masks in numpy files. “BRATS2013_Syn_Flair_Train_X.npy” contains input images and “BRATS2013_Syn_Flair_Train_S.npy” contains segmentation masks only.

it's hard for me to acquire BRATS2013 dataset ,could u please show me how to get it or send me one ,thx
lichen14@hotmail.com

**Comment by lichen14** [comment]
> We generated those 2 files ourselves from BRATS 2013 dataset. We use synthetic flair images particularly and saved them with there ground truth masks in numpy files. “BRATS2013_Syn_Flair_Train_X.npy” contains input images and “BRATS2013_Syn_Flair_Train_S.npy” contains segmentation masks only.

could you please explain more detail? thx, i get this trouble now
