### ISSUE TITLE
Provide Pre-trained models

### ISSUE THREAD

**Issue by harsharaman** [MrGiovanni/UNetPlusPlus#60]
Hi,
Since the scores on Medical Segmentation Liver Dataset is already available, could you please provide those pre-trained models so that we can download the model and compare with our own data?
Thanks.

**Comment by MrGiovanni** [comment]
Hi @harsharaman 

Certainly, please find the pre-trained models for the liver dataset here:

- Google Drive: https://drive.google.com/drive/folders/1mY6nOoL9ddHyFqNIKqBN9l3GhPegye8H?usp=sharing
- Baidu Drive: https://pan.baidu.com/s/1qd1GXKRIUL4k6OaSSMIJOg (Code: ppau)

We will also update the Github page shortly.

Thanks,
Zongwei and Shivam
