### ISSUE TITLE
dice_coef_loss

### ISSUE THREAD

**Issue by YJonmo** [MrGiovanni/UNetPlusPlus#8]
Hi there,

Thanks for the code.

I get this error that 'dice_coef_loss' is not defined.

**Comment by MrGiovanni** [comment]
'dice_coef_loss' function was defined in model_logic.py.
See line 38 in 'BRATS2013_application.py': from model_logic import *
Sorry for the confusion, but I changed the python file name 'model.py' to 'model_logic.py' before. Now fixed. Thanks!
