### ISSUE TITLE
Train own data

### ISSUE THREAD

**Issue by Lovesuu** [MrGiovanni/UNetPlusPlus#9]
Thanks for yours source, but can you  describe more clearly how can I train own data? I'm a student and want to try with my data includes images and the corresponding mask about the object.

**Comment by mahfuzmohammad** [comment]
Hi @Lovesuu,
An example code is already provided in the README.md (https://github.com/MrGiovanni/UNetPlusPlus#code-examples-for-your-own-data).

There you will find variables **x** and **y**. You need to load your images in **x** and masks into **y**. The value range of these variables needs to be normalized between [0, 1]. That's it!


Hope it helps!
